
import { Oswald, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/navbar/Navbar";
import Footer from "./_components/footer/Footer";

const OswaldFont = Oswald({
  variable: "--font-Oswald",
  subsets: ["latin"],
});

const RobotoFont = Roboto({
  variable: "--font-Roboto",
  subsets: ["latin"],
});


export const metadata = {
  title: "Fitness GYM",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="assets/img/icon.png" />

      </head>
      <body
        className={`${OswaldFont.variable} ${RobotoFont.variable} w-full mx-auto bg-white`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
